require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety
AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - spec/factories/**/*.rb
RSpec/ImplicitSubject:
  Exclude:
    - spec/factories/**/*.rb
RSpec/ImplicitExpect:
  Exclude:
    - spec/factories/**/*.rb
