module Esquery
  class Exists
    def initialize: (String field) -> void
    def to_h: () -> {
      exists: {
        field: String
      }
    }

    private

    attr_reader field: String
  end
end
